sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '9'
  - '10'
  - '12'
  - '13'
before_install:
  - if [[ "`node --version`" = v4* ]]; then
      npm install npm@latest-5 -g;
    else
      npm install npm@latest -g;
    fi
  - npm --version
script:
  - node --version
  - npm run travis
